import ξ from 'mithril';
import base from './base';
import editor from './editor';

export default class Home implements ClassComponent {
  view(vnode: CVNode) {
    return ξ(base,
        ξ('.ui.two.column.stackable.grid', [
          ξ('.ui.ten.wide.column',
              ξ('p', 'Please write your fabulous code below:'),
              ξ('.ui.segment.inverted',
                  ξ(editor)
              ),
          ),
          ξ('.ui.six.wide.column',
              ξ('p', 'Problems detected:'),
              ξ('.ui.segment.inverted[style=overflow: auto; max-height: 35em;]',
                  ξ('.ui.relaxed.list.divided',
                      ξ('.item',
                          ξ('i.big.frown.icon[style=color: #dc322f;]'),
                          ξ('.content',
                              ξ('.header[style=color: #dc322f;]',
                                  'E544: A very serious error [32:11]'),
                              ξ('.description',
                                  'Don\'t do this again, okay?!'),
                          ),
                      ),
                      ξ('.item',
                          ξ('i.big.meh.icon[style=color: #b58900;]'),
                          ξ('.content',
                              ξ('.header[style=color: #b58900;]',
                                  'W419: A not-so-serious warning [11:43]'),
                              ξ('.description',
                                  'It\'s still bad, mkay?'),
                          ),
                      ),
                      ξ('.item',
                          ξ('i.big.meh.icon[style=color: #b58900;]'),
                          ξ('.content',
                              ξ('.header[style=color: #b58900;]',
                                  'W419: A not-so-serious warning [11:43]'),
                              ξ('.description',
                                  'It\'s still bad, mkay?'),
                          ),
                      ),
                      ξ('.item',
                          ξ('i.big.meh.icon[style=color: #b58900;]'),
                          ξ('.content',
                              ξ('.header[style=color: #b58900;]',
                                  'W419: A not-so-serious warning [11:43]'),
                              ξ('.description',
                                  'It\'s still bad, mkay?'),
                          ),
                      ),
                      ξ('.item',
                          ξ('i.big.meh.icon[style=color: #b58900;]'),
                          ξ('.content',
                              ξ('.header[style=color: #b58900;]',
                                  'W419: A not-so-serious warning [11:43]'),
                              ξ('.description',
                                  'It\'s still bad, mkay?'),
                          ),
                      ),
                      ξ('.item',
                          ξ('i.big.meh.icon[style=color: #b58900;]'),
                          ξ('.content',
                              ξ('.header[style=color: #b58900;]',
                                  'W419: A not-so-serious warning [11:43]'),
                              ξ('.description',
                                  'It\'s still bad, mkay?'),
                          ),
                      ),
                      ξ('.item',
                          ξ('i.big.meh.icon[style=color: #b58900;]'),
                          ξ('.content',
                              ξ('.header[style=color: #b58900;]',
                                  'W419: A not-so-serious warning [11:43]'),
                              ξ('.description',
                                  'It\'s still bad, mkay?'),
                          ),
                      ),
                      ξ('.item',
                          ξ('i.big.meh.icon[style=color: #b58900;]'),
                          ξ('.content',
                              ξ('.header[style=color: #b58900;]',
                                  'W419: A not-so-serious warning [11:43]'),
                              ξ('.description',
                                  'It\'s still bad, mkay?'),
                          ),
                      ),
                      ξ('.item',
                          ξ('i.big.meh.icon[style=color: #b58900;]'),
                          ξ('.content',
                              ξ('.header[style=color: #b58900;]',
                                  'W419: A not-so-serious warning [11:43]'),
                              ξ('.description',
                                  'It\'s still bad, mkay?'),
                          ),
                      ),
                      ξ('.item',
                          ξ('i.big.meh.icon[style=color: #b58900;]'),
                          ξ('.content',
                              ξ('.header[style=color: #b58900;]',
                                  'W419: A not-so-serious warning [11:43]'),
                              ξ('.description',
                                  'It\'s still bad, mkay?'),
                          ),
                      ),
                      ξ('.item',
                          ξ('i.big.meh.icon[style=color: #b58900;]'),
                          ξ('.content',
                              ξ('.header[style=color: #b58900;]',
                                  'W419: A not-so-serious warning [11:43]'),
                              ξ('.description',
                                  'It\'s still bad, mkay?'),
                          ),
                      ),
                      ξ('.item',
                          ξ('i.big.meh.icon[style=color: #b58900;]'),
                          ξ('.content',
                              ξ('.header[style=color: #b58900;]',
                                  'W419: A not-so-serious warning [11:43]'),
                              ξ('.description',
                                  'It\'s still bad, mkay?'),
                          ),
                      ),
                      ξ('.item',
                          ξ('i.big.meh.icon[style=color: #b58900;]'),
                          ξ('.content',
                              ξ('.header[style=color: #b58900;]',
                                  'W419: A not-so-serious warning [11:43]'),
                              ξ('.description',
                                  'It\'s still bad, mkay?'),
                          ),
                      ),
                      ξ('.item',
                          ξ('i.big.meh.icon[style=color: #b58900;]'),
                          ξ('.content',
                              ξ('.header[style=color: #b58900;]',
                                  'W419: A not-so-serious warning [11:43]'),
                              ξ('.description',
                                  'It\'s still bad, mkay?'),
                          ),
                      ),
                  ),
              ),
          ),
        ])
    );
  }
};
