import ξ from 'mithril';
import base from './base';
import editor from './editor';

export default class Home implements ClassComponent {
  view(vnode: CVNode) {
    return ξ(base,
        ξ('div[style=height: 100%; overflow: hidden;]',
            ξ('.ui.two.column.stackable.grid[style=height: 100%; margin: 0;]', [
              ξ('.ui.ten.wide.column[style=padding: 0;]',
                  ξ(editor)
              ),
              ξ('.ui.six.wide.column',
                  ξ('.ui.relaxed.list.divided',
                      ξ('.item',
                          ξ('i.big.frown.icon[style=color: #dc322f;]'),
                          ξ('.content',
                              ξ('.header[style=color: #dc322f;]',
                                  'E544: A very serious error [32:11]'),
                              ξ('.description',
                                  'Don\'t do this again, okay?!'),
                          ),
                      ),
                      ξ('.item',
                          ξ('i.big.meh.icon[style=color: #b58900;]'),
                          ξ('.content',
                              ξ('.header[style=color: #b58900;]',
                                  'W419: A not-so-serious warning [11:43]'),
                              ξ('.description',
                                  'It\'s still bad, mkay?'),
                          ),
                      ),
                      ξ('.item',
                          ξ('i.big.meh.icon[style=color: #b58900;]'),
                          ξ('.content',
                              ξ('.header[style=color: #b58900;]',
                                  'W419: A not-so-serious warning [11:43]'),
                              ξ('.description',
                                  'It\'s still bad, mkay?'),
                          ),
                      ),
                      ξ('.item',
                          ξ('i.big.meh.icon[style=color: #b58900;]'),
                          ξ('.content',
                              ξ('.header[style=color: #b58900;]',
                                  'W419: A not-so-serious warning [11:43]'),
                              ξ('.description',
                                  'It\'s still bad, mkay?'),
                          ),
                      ),
                      ξ('.item',
                          ξ('i.big.meh.icon[style=color: #b58900;]'),
                          ξ('.content',
                              ξ('.header[style=color: #b58900;]',
                                  'W419: A not-so-serious warning [11:43]'),
                              ξ('.description',
                                  'It\'s still bad, mkay?'),
                          ),
                      ),
                      ξ('.item',
                          ξ('i.big.meh.icon[style=color: #b58900;]'),
                          ξ('.content',
                              ξ('.header[style=color: #b58900;]',
                                  'W419: A not-so-serious warning [11:43]'),
                              ξ('.description',
                                  'It\'s still bad, mkay?'),
                          ),
                      ),
                      ξ('.item',
                          ξ('i.big.meh.icon[style=color: #b58900;]'),
                          ξ('.content',
                              ξ('.header[style=color: #b58900;]',
                                  'W419: A not-so-serious warning [11:43]'),
                              ξ('.description',
                                  'It\'s still bad, mkay?'),
                          ),
                      ),
                      ξ('.item',
                          ξ('i.big.meh.icon[style=color: #b58900;]'),
                          ξ('.content',
                              ξ('.header[style=color: #b58900;]',
                                  'W419: A not-so-serious warning [11:43]'),
                              ξ('.description',
                                  'It\'s still bad, mkay?'),
                          ),
                      ),
                      ξ('.item',
                          ξ('i.big.meh.icon[style=color: #b58900;]'),
                          ξ('.content',
                              ξ('.header[style=color: #b58900;]',
                                  'W419: A not-so-serious warning [11:43]'),
                              ξ('.description',
                                  'It\'s still bad, mkay?'),
                          ),
                      ),
                      ξ('.item',
                          ξ('i.big.meh.icon[style=color: #b58900;]'),
                          ξ('.content',
                              ξ('.header[style=color: #b58900;]',
                                  'W419: A not-so-serious warning [11:43]'),
                              ξ('.description',
                                  'It\'s still bad, mkay?'),
                          ),
                      ),
                      ξ('.item',
                          ξ('i.big.meh.icon[style=color: #b58900;]'),
                          ξ('.content',
                              ξ('.header[style=color: #b58900;]',
                                  'W419: A not-so-serious warning [11:43]'),
                              ξ('.description',
                                  'It\'s still bad, mkay?'),
                          ),
                      ),
                      ξ('.item',
                          ξ('i.big.meh.icon[style=color: #b58900;]'),
                          ξ('.content',
                              ξ('.header[style=color: #b58900;]',
                                  'W419: A not-so-serious warning [11:43]'),
                              ξ('.description',
                                  'It\'s still bad, mkay?'),
                          ),
                      ),
                      ξ('.item',
                          ξ('i.big.meh.icon[style=color: #b58900;]'),
                          ξ('.content',
                              ξ('.header[style=color: #b58900;]',
                                  'W419: A not-so-serious warning [11:43]'),
                              ξ('.description',
                                  'It\'s still bad, mkay?'),
                          ),
                      ),
                      ξ('.item',
                          ξ('i.big.meh.icon[style=color: #b58900;]'),
                          ξ('.content',
                              ξ('.header[style=color: #b58900;]',
                                  'W419: A not-so-serious warning [11:43]'),
                              ξ('.description',
                                  'It\'s still bad, mkay?'),
                          ),
                      ),
                  ),
                  ξ('.ui.column.grid', [
                    ξ('.six.wide.column',
                        ξ(`select.ui.fluid.selection.dropdown[style=\
                border: none;\
                -webkit-appearance: none;\
                -moz-appearance: none;\
                appearance: none;]`, [

                          ξ('option', {value: 'python3'}, 'Python 3'),
                          ξ('option', {value: 'python2'}, 'Python 2.7'),
                        ])
                    ),
                    ξ('.four.wide.column'),
                    ξ('.six.wide.column',
                        ξ('button.ui.big.fluid.primary.button', 'ROAST ME!')
                    ),
                  ]),
              ),
            ])
        )
    );
  }
};
